version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - cd "Project2_AirBNB_Stream_Data_Proj_SQS"
      # - pip install -r requirements.txt -t lib
  build:
    commands:
      # - echo "Zipping deployment package..."
      # - cd lib
      # - zip -r9 ../deployment_package.zip .
      # - cd ..
      # - zip -g deployment_package.zip lambda_producer_airbnb_mock_gen.py
      - zip -r deployment_package.zip lambda_producer_airbnb_mock_gen.py
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment_package.zip s3://lambda-buildszip2/
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name s3-lambda-dataprocg-delivry --s3-bucket lambda-buildszip2 --s3-key deployment_package.zip
      - echo "Deployment complete!"